### ISSUE TITLE
Repositories I contribute to are not listed

### ISSUE THREAD

**Issue by julienXX** [gitscout/gitscout-feedback#21]
I'd like to see the repositories I contribute to, my work repos for example are not listed.

**Comment by jeremybenaim** [comment]
Hey @julienXX 

In order to have access to your work repos you need to ask an admin of the concerned organization to enable third-party apps in the org settings

Looks like this:

<img width="1035" alt="capture d ecran 2016-07-26 a 16 42 55" src="https://cloud.githubusercontent.com/assets/181291/17142489/9a1c449c-5350-11e6-829f-156386baa356.png">

Once this is done, restarting the app should do the trick! 

Thanks :)

**Comment by julienXX** [comment]
Thanks @jeremybenaim!
