### ISSUE TITLE
Question: Can I access Repositories I am following?

### ISSUE THREAD

**Issue by briannhinton** [gitscout/gitscout-feedback#25]
Is it possible to view Repositories that I'm following? So I can review issues, contribute and add my own issues?

**Comment by jeremybenaim** [comment]
@brianhinton do you mean by "following" the repos you are "watching" or "starred"? Thanks! :)

**Comment by briannhinton** [comment]
I like that notification btw. :)

What I mean is that right now I have my Repositories showing up in the sidebar, and gitscout-feedback. 

I'm working with a few organizations where I'm not a member of the organization, but I want to be able to review issues.

**Comment by briannhinton** [comment]
Would be useful to be able to view "watching" Repositories as well.

**Comment by jeremybenaim** [comment]
Thanks for these precisions. :)

Actually we're currently working on a way to add any repo you can access. From, let's say, [facebook/react](https://github.com/facebook/react) to other repos you working with but without being part of the organization as you mentioned earlier.

That being said, these specific repos should show up if you are a contributor on them. So my guess is that they could be hidden because the concerned organization didn't enable third party app in their settings (see #21)

Anyway, this feature is almost ready (needs some ui polishing) and should be live in a week or two 😉 

( and glad you like the notification 😄  )

**Comment by briannhinton** [comment]
Ok. Thanks. I look forward to the updates.
