### ISSUE TITLE
Design: Closed vs open issues

### ISSUE THREAD

**Issue by briannhinton** [gitscout/gitscout-feedback#27]
The color isn't quite enough to visualize close vs open issues.

Suggestions:

Add a door icon next to each #number that is open for open issues and closed for closed issues. Though this might be too elaborate.

Simply add text that says closed or open next to the #number.

**Comment by Adrien-Griveau** [comment]
@briannhinton We are going to try different version to see. From now I think we can spot the closed and the open pretty easely. Adding icons might make the list look to overwhelming.

Thanks for you feedback Iet you know when we realese a new update about it.
 
✌️

**Comment by jeroldangarcia** [comment]
Maybe not an Ico.... but a "state" filter in the search box could do it...

**Comment by briannhinton** [comment]
I still feel this isn't communicated clearly.

**Comment by jeroldangarcia** [comment]
+1 @briannhinton

**Comment by Adrien-Griveau** [comment]
@briannhinton @jeroldangarcia what do you think about something like this?


![Capture d’écran 2016-09-01 à 09.53.05](http://static.gitscout.com/718e5ab506ac17a51cb2988fff66ae0a29a66697a20de61ac18e636cd48136b8.png)

**Comment by jeroldangarcia** [comment]
I would like to filter or at least to group/reorder bytes state

El 1/9/2016 3:54 PM, "Adrien Griveau" <notifications@github.com> escribió:

@briannhinton <https://github.com/briannhinton> @jeroldangarcia
<https://github.com/jeroldangarcia> what do you think about something like
this?

[image: Capture d’écran 2016-09-01 à 09.53.05]
<https://camo.githubusercontent.com/eb108a1843766238b39b53275492a54fd4a40021/687474703a2f2f7374617469632e67697473636f75742e636f6d2f373138653561623530366163313761353163623239383866666636366165306132396136363639376132306465363161633138653633366364343831333662382e706e67>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/gitscout/gitscout-feedback/issues/27#issuecomment-244085709>,
or mute the thread

**Comment by Adrien-Griveau** [comment]
@jeroldangarcia We can try to find a way to fix this. You can use the search now by doing this 
![Capture d’écran 2016-09-02 à 10.22.56](http://static.gitscout.com/963dbae40915c86bd590095caaaacf9db04da34f0ad78cbfc3a0273e0f9d19cb.png)

**Comment by jeremybenaim** [comment]
@briannhinton @jeroldangarcia how do you like the new design? We tried to make it easier to distinguish closed & opened issues.
Let us know if you still find it confusing, thanks! 🙂

**Comment by jeroldangarcia** [comment]
nice!!! 
bold fonts for open and disabled style for closed issues do it for me!!!!

**Comment by jeremybenaim** [comment]
![yeah](http://i.giphy.com/xT5LMPw4133KKkpzEc.gif)
