### ISSUE TITLE
Cross project list of issues

### ISSUE THREAD

**Issue by ForbesLindesay** [gitscout/gitscout-feedback#32]
Only seeing issues on a per repo basis is rarely useful.   For this tool to be of any use I need to be able to save and use searches of issues that span multiple repos.  e.g.
1. All open issues in the jstransformers org.
2. All open pull requests across all the repositories I have commit access to.

I'd also need advanced serach/filter capabilities such as: issues that are open or have been commented on by me or where I have been mentioned (i.e. if an issue was opened and closed without me ever seeing it, I probably don't want to ever see it).

**Comment by jeremybenaim** [comment]
@ForbesLindesay thanks to share this, that's very interesting

Saved search are definitely on our mind, we're not sure yet how to make them nice enough to be usable though

As for pull requests we decided not to support them for the moment since they are really specific in term of UX and once we'd have nailed the issues that'd be a cool challenge to add them to Gitscout :)

For the UX of the search we're currently working on a new version that'll be probably more intuitive, should be live in the next major release (in a few weeks min.) and I'll notify you once we release it ;)
