### ISSUE TITLE
Bug: When repository is selected you can't hide it

### ISSUE THREAD

**Issue by briannhinton** [gitscout/gitscout-feedback#38]
Steps to reproduce:
1. Make sure one of your repositories is selected. It will be highlighted in the sidebar.
2. Go into preferences and then select the repositories section.
3. Uncheck "Show all repositories" for the group that the selected repository is located in. OR you can simply uncheck the selected repository individually.

Note: The repository will go away when it is no longer selected, but that is still a confusing experience.

**Comment by jeremybenaim** [comment]
@briannhinton good catch, thanks ! :)

Except it's not reeally a bug, rather a UX flaw we need to improve :/

It's just that we introduced the ability to access repos that aren't in your sidebar with the quick switcher and because of that there's this weird state of "selected-repo-but-not-in-my-sidebar-so-it-will-disappear-because-it-shouldnt-be-here" which I concede isn't clear at all

So, yeah we'll try to make this experience less confusing in the upcoming releases and thanks again for pointing it out! :)

**Comment by jeremybenaim** [comment]
(Not sure the previous comment makes sense to you, let us know if you're still confused!)

**Comment by briannhinton** [comment]
Your explanation made perfect sense. 

My recommendation is that you just have it go away. You didn't switch to display the repository from the 'quick switcher' state -- so it doesn't make sense that it stays in the view.

Another approach is adding vivid color (yellow?) that communicates something is different with this highlighted repository. Or maybe add an up-down arrow icon in the quick switcher field, and display that icon next to repositories that are in this temporary selected state.

**Comment by jeremybenaim** [comment]
@briannhinton does the new design solves this weird UX behaviour? We tried to make it actually simpler, as long as the repo is selected it'll remain in the sidebar but once you select another one it will disappear
