### ISSUE TITLE
Don't auto watch your own feedback repo

### ISSUE THREAD

**Issue by josefdlange** [gitscout/gitscout-feedback#62]
I'm glad to provide feedback when I encounter something, but receiving email notifications without having recollection of voluntarily watching a repo really rubs me the wrong way.

Unless this was specifically called out in the OAuth process and I missed it -- that would be my fault but even then a little frustrating -- I think it's a bit unseemly to do this.

**Comment by Albarahakami** [comment]
I agree

**Comment by FanaHOVA** [comment]
+1

**Comment by EduardoRT** [comment]
Yeah, annoying and shady.

**Comment by lquessenberry** [comment]
I started receiving emails from this repo as well just by signing in. I may have skipped over the OAuth process too.

**Comment by selfagency** [comment]
it's beta software. they want you to provide feedback. you have to watch the repo for gitscout to put it in your sidebar. is that really so much to ask for free access to a great up-and-coming piece of software?

**Comment by jakeleboeuf** [comment]
@selfagency spam is spam

**Comment by timkendall** [comment]
Yeah pretty lame move. If I actually started using the app I would provide feedback on my own without the need to be subscribed to the repo.

**Comment by opragel** [comment]
I saw a bunch of notifications showing up in my inbox, lo and behold, they were notifications about getting notifications from this repo. Please disable this.

**Comment by lleger** [comment]
Yeah, this is a pretty "not cool" move. Suddenly my inbox was filled with emails! Please remove.

**Comment by jeremybenaim** [comment]
Hello you all,

First of all thanks @josefdlange for opening this issue.

We hear you and completely understand, and sincerely apologize for that! 😔

We've been in private beta for a few months with that system and had no complaints. As @selfagency pointed out, that was a great way to quickly get feedback and it felt unobtrusive for users, we figured it would be ok to keep it that way.

Our goal is to be rather useful than spammy, so be sure that we're going to fix that really soon! 

We'll be releasing a new version in a few days that will prompt the user and ask wether they want to add the gitscout-feedback repo to their list or not at signup to prevent this to happen in the future.

Meanwhile, you can hide Gitscout from your settings in the repositories tab like this: 
![repo_settings](https://pbs.twimg.com/media/CzJ5jnCXAAEDQ-2.jpg:large)

You can also manage your notifications settings for the repo from here: https://github.com/gitscout/gitscout-feedback/subscription

We hope you will give Gitscout a second chance and that it will make you smile rather than frown! 😉

Thanks! :pray:

**Comment by sindresorhus** [comment]
This is not ok! Reported to GitHub. App uninstalled.

**Comment by douglascamata** [comment]
The very first thing the app does is act without the consent of the user. So my first impression is that I can trust this app. This should be hotfixed as soon as possible if you don't want to lose more users.

**Comment by dm** [comment]
+1

**Comment by steve228uk** [comment]
Deleted. Don't appreciate being spammed like this.

**Comment by jeremybenaim** [comment]
Ok folks, we just pushed an updated and removed the autowatch at signup, thanks for reporting it.

**Comment by jeremybenaim** [comment]
Again our goal never was to spam you or anything like that and I truly hope you understand and that it won't prevent you from using the app in the future.

We've been working really hard for months to release this first public version and it really saddens me that because of this little clumsiness some of you wouldn't even consider using it. :pensive:

That being said, again, I understand and I might have reacted just like you.

But I hope you'll understand us too.

I'll say it again but our goal is to build a high-quality product and we all know that user's feedback is crucial for that.

We never meant to spam you. Really.

Peace :v:

**Comment by selfagency** [comment]
@jakeleboeuf actually, under federal law, it's not spam if you consciously downloaded and installed their product, which would be considered initiating a relationship and thereby welcoming communications. it also isn't spam if you turn off email notifications for repos and just use gitscout to provide desktop notifications. but whatevs. you guys got what you wanted.

**Comment by lquessenberry** [comment]
I love the software by the way. I just didn't expect the new subscription is all. Thanks for the good work and keep it up. Those that deleted it for now, I hope you give it a second chance.

**Comment by omartineau** [comment]
A very bad idea !
It's SPAM. I don't want to recive noticiation from your github issues

**Comment by supermarin** [comment]
what a fucking mess

**Comment by Adrien-Griveau** [comment]
We fixed the issue. Sorry about that again. 

Closing the issue.
